[package]
name = "rust_atomic_lock"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "thread"
path = "src/ss_1/thread.rs"

[[bin]]
name = "thread_scope"
path = "src/ss_1/thread_scope.rs"

[[bin]]
name = "thread_static"
path = "src/ss_1/thread_static.rs"

[[bin]]
name = "mutable"
path = "src/ss_1/mutable.rs"

[[bin]]
name = "mutex"
path = "src/ss_1/mutex.rs"

[dependencies]
