[package]
name = "rust_atomic_lock"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "thread"
path = "src/ss_1/thread.rs"

[[bin]]
name = "thread_scope"
path = "src/ss_1/thread_scope.rs"

[dependencies]
